diccionarioEquipos = {
    "Real Betis": "Sevilla",
    "Sevilla FC": "Sevilla",
    "Real Madrid": "Madrid",
    "Atlético de Madrid": "Madrid",
    "FC Barcelona": "Barcelona",
    "Espanyol": "Barcelona",
    "Valencia CF": "Valencia",
    "Villarreal CF": "Villarreal",
    "Athletic Club": "Bilbao",
    "Real Sociedad": "San Sebastián",
    "Celta de Vigo": "Vigo",
    "Real Valladolid": "Valladolid",
    "Osasuna": "Pamplona",
    "Real Zaragoza": "Zaragoza",
    "Getafe CF": "Getafe",
    "Rayo Vallecano": "Madrid",
    "Deportivo Alavés": "Vitoria-Gasteiz",
    "Real Mallorca": "Palma de Mallorca",
    "Girona FC": "Girona",
    "UD Las Palmas": "Las Palmas",
}

